-- Run this once in Supabase Dashboard > SQL Editor.
-- It is safe to run if the table already exists.

CREATE TABLE IF NOT EXISTS public.certificates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  image_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_certificates_created_at
  ON public.certificates(created_at);

ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read certificates" ON public.certificates;
CREATE POLICY "Allow public read certificates"
  ON public.certificates FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Admin can manage certificates" ON public.certificates;
CREATE POLICY "Admin can manage certificates"
  ON public.certificates FOR ALL
  TO authenticated
  USING ((auth.jwt() ->> 'email') = 'dayalprashant766@gmail.com')
  WITH CHECK ((auth.jwt() ->> 'email') = 'dayalprashant766@gmail.com');
