-- Run this once in Supabase Dashboard > SQL Editor.
-- Creates the comments table and public access rules.

CREATE TABLE IF NOT EXISTS public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  comment text NOT NULL,
  image_url text,
  likes integer NOT NULL DEFAULT 0,
  is_pinned boolean NOT NULL DEFAULT false,
  replies jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_comments_created_at
  ON public.comments(created_at);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read comments" ON public.comments;
CREATE POLICY "Allow public read comments"
  ON public.comments FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Allow public insert comments" ON public.comments;
CREATE POLICY "Allow public insert comments"
  ON public.comments FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Admin can manage comments" ON public.comments;
CREATE POLICY "Admin can manage comments"
  ON public.comments FOR ALL
  TO authenticated
  USING ((auth.jwt() ->> 'email') = 'dayalprashant766@gmail.com')
  WITH CHECK ((auth.jwt() ->> 'email') = 'dayalprashant766@gmail.com');
