-- Run this once in Supabase Dashboard > SQL Editor.
-- Creates the tech_stack table and public read access.

CREATE TABLE IF NOT EXISTS public.tech_stack (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  logo_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tech_stack_created_at
  ON public.tech_stack(created_at);

ALTER TABLE public.tech_stack ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read tech_stack" ON public.tech_stack;
CREATE POLICY "Allow public read tech_stack"
  ON public.tech_stack FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Admin can manage tech_stack" ON public.tech_stack;
CREATE POLICY "Admin can manage tech_stack"
  ON public.tech_stack FOR ALL
  TO authenticated
  USING ((auth.jwt() ->> 'email') = 'dayalprashant766@gmail.com')
  WITH CHECK ((auth.jwt() ->> 'email') = 'dayalprashant766@gmail.com');
